# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, verbose_name=b'Nombre empresa')),
                ('nombre', models.CharField(max_length=100, verbose_name=b'Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name=b'Apellido')),
                ('email', models.EmailField(max_length=100, verbose_name=b'email')),
                ('telefono', models.CharField(max_length=10, verbose_name=b'Telefono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
